language: rust
notifications:
    irc: "irc.mozilla.org#piston-internals"
os:
    - linux
    - osx
env:
    global:
        - secure: cMj2eu4gnI5+kWD9rBNL51IARXpy6D/imoqVaYcqFuGUGGCY66qdwq/ZfBh+GRJAVEMkvRn7QWwf6KQOjAun6aVs4d85c3/QNMqe+XTi9tcG11lQW3nUCibTavv+gM9EX7vJKCfOvZaqFPmUW4ez8ttppXcvdcHEBMTkWUxTWZM=
        - LD_LIBRARY_PATH: /usr/local/lib
before_install:
    - curl -O http://www.libsdl.org/release/SDL2-2.0.0.tar.gz
    - tar -xzvf SDL2-2.0.0.tar.gz
install:
    - (cd SDL2-2.0.0 && ./configure && make && sudo make install)
before_script:
    - rustc -v
    - cargo -V
script:
    - cargo build -v
    - cargo test -v
    - cargo doc -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -rf doc
