[package]

name = "sdl2_game_window"
version = "0.0.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>"]
tags = []

[dependencies.sdl2]

git = "https://github.com/AngryLawyer/rust-sdl2"

[dependencies.event]

git = "https://github.com/pistondevelopers/event"

[dependencies.shader_version]

git = "https://github.com/pistondevelopers/shader_version"

[dependencies.input]

git = "https://github.com/pistondevelopers/input"

[dependencies.gl]

git = "https://github.com/bjz/gl-rs"

[lib]

name = "sdl2_game_window"
path = "src/lib.rs"
